Repository rakutentech/ios-miniapp, pull requests merged in 2020-07, with the labels that each got.

#95 Show build version in Settings
  Example/SettingsTableViewController.swift
Labels: Enhancement, feature-request

#96 Added support different mime types
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/MimeTypes.swift
  MiniApp/Classes/Display/URLSchemeHandler.swift
  Tests/Unit/MimeTypesTests.swift
  Tests/Unit/MiniAppViewTests.swift
Labels: bug-fix

#99 Changes in config files to update reports to Codecov
  .codecov.yml
  .travis.yml
  README.md
Labels: Enhancement

#97 SDK and sample app changes for requesting location permission
  Example/Info.plist
  Example/ViewController+MiniApp.swift
  Example/ViewController.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/JavascriptBridge/bridge.js
  MiniApp/Classes/Models/MiniAppJavaScriptMessageInfo.swift
  MiniApp/Classes/Protocols/MiniAppMessageProtocol.swift
  MiniApp/Classes/RealMiniApp.swift
  MiniApp/ViewController+MiniAppMessageProtocol.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/RealMiniAppTests.swift
Labels: feature-request

#98 Feature/test epic
  Example/Array+MiniApp.swift
  Example/Base.lproj/Main.storyboard
  Example/Config.swift
  Example/Info.plist
  Example/Number+MiniApp.swift
  Example/SettingsTableViewController.swift
  Example/ViewController+MiniApp.swift
  Example/ViewController.swift
  Gemfile
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/API/ListingAPI.swift
  MiniApp/Classes/API/ManifestAPI.swift
  MiniApp/Classes/Environment.swift
  MiniApp/Classes/Extensions/Bundle+Environment.swift
  MiniApp/Classes/MiniAppClient.swift
  MiniApp/Classes/MiniAppSdkConfig.swift
  MiniApp/Classes/RealMiniApp.swift
  MiniApp/en.lproj/Localizable.strings
  Podfile.lock
  README.md
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppClientTests.swift
  Tests/Unit/MiniAppLoggerTests.swift
  Tests/Unit/RealMiniAppTests.swift
Labels: Enhancement, Refactoring, documentation, feature-request

#105 Custom user agent append in WebView
  Example/Info.plist
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/MiniAppWebView.swift
  MiniApp/Classes/Environment.swift
  MiniApp/Classes/MiniAppSdkConfig.swift
  README.md
  Tests/Unit/EnvironmentTests.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppSdkConfigTests.swift
  Tests/Unit/RealMiniAppViewTests.swift
Labels: feature-request

#107 Demo app file stored at wrong path
  Example/ViewController+MiniAppMessageProtocol.swift
  MiniApp.xcodeproj/project.pbxproj
Labels: Enhancement

#109 Updated UA string - sync with Android side
  Example/Info.plist
  MiniApp.xcodeproj/project.pbxproj
  Tests/Unit/RealMiniAppViewTests.swift
Labels: Enhancement

#110 Offline loading issue fix
  MiniApp/Classes/RealMiniApp.swift
Labels: bug-fix

#108 Enable override localizable strings from Host app
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/RealMiniAppView+WKUIDelegate.swift
  MiniApp/Classes/Extensions/MiniApp+String.swift
  Tests/Unit/MiniApp+StringTests.swift
Labels: Enhancement

#115 Feature/build secrets
  .travis.yml
  Example/Config/Config-debug.xcconfig
  Example/Config/Config-release.xcconfig
  Example/Info.plist
  MiniApp.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
  Tests/Unit/MiniAppStorageTests.swift
  appcenter-post-clone.sh
  configure-secrets.sh
  fastlane/Fastfile
Labels: Enhancement, Refactoring

#114 Location - Get current location override from SDK
  MiniApp/Classes/Extensions/MiniApp+Date.swift
  MiniApp/Classes/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/JavascriptBridge/bridge.js
  MiniApp/Classes/Models/MiniAppJavaScriptMessageInfo.swift
  Podfile.lock
  Tests/Unit/DisplayerTests.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
Labels: feature-request
