Repository rakutentech/ios-miniapp, pull requests merged in 2020-04, with the labels that each got.

#45 Updated testcases for RealMini app
  MiniApp.xcodeproj/project.pbxproj
  Tests/Unit/Helpers.swift
  Tests/Unit/RealMiniAppTests.swift
Labels: Enhancement

#46 Removed MiniAppView and moved the code to RealMiniAppView
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/Displayer.swift
  MiniApp/Classes/Display/MiniAppView.swift
  MiniApp/Classes/Display/RealMiniAppView.swift
  Tests/Unit/DisplayerTests.swift
  Tests/Unit/MiniAppViewTests.swift
  Tests/Unit/RealMiniAppTests.swift
  Tests/Unit/RealMiniAppViewTests.swift
Labels: Refactoring

#50 Added version tag in the list and few fixes
  Example/Base.lproj/Main.storyboard
  Example/SettingsTableViewController.swift
  Example/ViewController.swift
  MiniApp/Classes/Models/MiniAppInfo.swift
  MiniApp/MiniAppCell.swift
Labels: Enhancement

#55 Feature/ios javascript interface implementation
  MiniApp.podspec
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/Displayer.swift
  MiniApp/Classes/Display/MiniAppView.swift
  MiniApp/Classes/Display/RealMiniAppView.swift
  MiniApp/Classes/Extensions/MiniApp+WKUserContentController.swift
  MiniApp/Classes/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/JavascriptBridge/bridge.js
  MiniApp/Classes/Models/MiniAppJavaScriptMessageInfo.swift
  MiniApp/Classes/Protocols/MiniAppMessageProtocol.swift
  MiniApp/Classes/RealMiniApp.swift
  MiniApp/Classes/Utilities/Constants.swift
  Podfile.lock
  Tests/Unit/DisplayerTests.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/RealMiniAppViewTests.swift
Labels: feature-request

#57 Optional value set for displayName in MiniAppInfo
  Example/Images.xcassets/app-list.imageset/Contents.json
  Example/ViewController.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Models/MiniAppInfo.swift
Labels: feature-request

#56 Feature/mini 858
  Example/Base.lproj/Main.storyboard
  Example/DisplayController.swift
  Example/DisplayNavigationController.swift
  Example/ViewController.swift
Labels: Enhancement, Refactoring, bug-fix, feature-request

#61 Silent updates
  Example/Progress+UIViewController.swift
  Example/UIImageView+Extensions.swift
  Example/ViewController+MiniApp.swift
  Example/ViewController.swift
  MiniApp.xcodeproj/project.pbxproj
Labels: Enhancement, Refactoring, feature-request

#59 Display error message when a non uuid (mini app) id format is entered
  Example/Progress+UIViewController.swift
  MiniApp/en.lproj/Localizable.strings
Labels: bug-fix

#63 Updating to latest JS bridging code
  MiniApp/Classes/JavascriptBridge/bridge.js
Labels: bridge-code

#62 Validations for AppID and Subscription key - MINI-578
  Example/Base.lproj/Main.storyboard
  Example/Config.swift
  Example/Progress+UIViewController.swift
  Example/SettingsTableViewController.swift
  Example/String+MiniApp.swift
  Example/ViewController.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/en.lproj/Localizable.strings
Labels: bug-fix

#69 Fixed issues related to validations in sample app
  Example/Base.lproj/Main.storyboard
  Example/Progress+UIViewController.swift
  Example/SettingsTableViewController.swift
  Example/ViewController+MiniApp.swift
  Example/ViewController.swift
  MiniApp/en.lproj/Localizable.strings
  Podfile.lock
Labels: bug-fix

#68 Feature/MINI-834
  Example/Base.lproj/Main.storyboard
  Example/Config.swift
  Example/FirstLaunchViewController.swift
  Example/Images.xcassets/curved-arrow.imageset/Contents.json
  Example/Images.xcassets/curved-arrow.imageset/curved-arrow.png
  Example/SettingsTableViewController.swift
  Example/ViewController+MiniApp.swift
  Example/ViewController.swift
  MiniApp.xcodeproj/project.pbxproj
  Podfile.lock
Labels: Enhancement, Refactoring, feature-request
