Repository rakutentech/ios-miniapp, pull requests merged in 2020-08, with the labels that each got.

#116 Remove run time config for User Agent
  Example/ViewController.swift
  MiniApp/Classes/Environment.swift
  MiniApp/Classes/MiniAppSdkConfig.swift
  README.md
  Tests/Unit/MiniAppSdkConfigTests.swift
Labels: Enhancement

#118 Update/refactor and changelog
  .travis.yml
  CHANGELOG.md
  MiniApp/Classes/Display/MiniAppNavigationConfig.swift
  MiniApp/Classes/Display/RealMiniAppView.swift
  MiniApp/Classes/DownloadOperation.swift
  MiniApp/Classes/MiniAppDownloader.swift
  README.md
  Tests/Unit/RealMiniAppViewTests.swift
  USERGUIDE.md
Labels: Enhancement, Refactoring

#106 Feature/zip epic
  MiniApp.podspec
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Extensions/MiniApp+URL.swift
  MiniApp/Classes/MiniAppClient.swift
  MiniApp/Classes/MiniAppDownloader.swift
  MiniApp/Classes/MiniAppLogger.swift
  Podfile.lock
  Tests/SmallMA.zip
  Tests/SmallMAerror.zip
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppDownloaderTests.swift
Labels: Enhancement, feature-request

#122 Public interface change - create mini app using appId
  CHANGELOG.md
  Example/ViewController+MiniApp.swift
  MiniApp/Classes/MiniApp.swift
  MiniApp/Classes/Models/MiniAppInfo.swift
  MiniApp/Classes/RealMiniApp.swift
  MiniApp/Classes/Storage/MiniAppStatus.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppStatusTests.swift
  Tests/Unit/RealMiniAppTests.swift
  USERGUIDE.md
Labels: feature-request

#121 Dialer support changes
  MiniApp/Classes/Display/RealMiniAppView.swift
  MiniApp/Classes/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
Labels: feature-request

#127 User profile settings - Name & Image from the library
  Example/Base.lproj/Main.storyboard
  Example/ContactsListSettingsTableViewController.swift
  Example/Images.xcassets/Rakuten-profile-image.imageset/Contents.json
  Example/Images.xcassets/Rakuten-profile-image.imageset/Rakuten.jpg
  Example/Images.xcassets/SF_lock.imageset/Contents.json
  Example/Images.xcassets/SF_lock.imageset/SF_lock.png
  Example/Images.xcassets/SF_lock.imageset/SF_lock@2x.png
  Example/Images.xcassets/SF_lock.imageset/SF_lock@3x.png
  Example/Images.xcassets/SF_person.imageset/Contents.json
  Example/Images.xcassets/SF_person.imageset/SF_person_badge_plus_fill.png
  Example/Images.xcassets/SF_person.imageset/SF_person_badge_plus_fill@2x.png
  Example/Images.xcassets/SF_person.imageset/SF_person_badge_plus_fill@3x.png
  Example/MiniApp+UIImage.swift
  Example/SettingsTableViewController.swift
  Example/String+MiniApp.swift
  Example/UserSettingsTableViewController.swift
  Example/en.lproj/Localizable.strings
  MiniApp.xcodeproj/project.pbxproj
  Podfile.lock
Labels: feature-request, sample-app
