Repository rakutentech/ios-miniapp, pull requests merged in 2020-02, with the labels that each got.

#17 Feature/downloading mini app
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Extensions/MiniApp+NSError.swift
  MiniApp/Classes/MiniAppClient.swift
  MiniApp/Classes/MiniAppDownloader.swift
  MiniApp/Classes/MiniAppStorage.swift
  MiniApp/Classes/Protocols/MiniAppDownloaderProtocol.swift
  MiniApp/Classes/RealMiniApp.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniApp+NSErrorTests.swift
  Tests/Unit/MiniAppDownloaderTests.swift
Labels: feature-request

#18 Feature/display mini app
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/Displayer.swift
  MiniApp/Classes/Display/MiniAppView.swift
  MiniApp/Classes/Display/MiniAppWebView.swift
  MiniApp/Classes/Display/RealMiniAppView.swift
  MiniApp/Classes/MiniAppView.swift
  Tests/Unit/DisplayerTests.swift
  Tests/Unit/MiniAppViewTests.swift
  Tests/Unit/RealMiniAppViewTests.swift
Labels: feature-request

#21 docs: PR template - change gradle command to fastlane command
  .github/pull_request_template.md
Labels: documentation

#20 Refactor: Display module
  MiniApp/Classes/Display/Displayer.swift
  MiniApp/Classes/Display/MiniAppView.swift
  MiniApp/Classes/Display/RealMiniAppView.swift
  MiniApp/Classes/MiniApp.swift
  MiniApp/Classes/Protocols/MiniAppDisplayProtocol.swift
  MiniApp/Classes/RealMiniApp.swift
  Tests/Unit/MiniAppViewTests.swift
Labels: Refactoring

#22 Updated createMiniApp method with interfaces
  MiniApp/Classes/Display/MiniAppWebView.swift
  MiniApp/Classes/MiniApp.swift
  MiniApp/Classes/RealMiniApp.swift
Labels: feature-request

#23 Feature: Sample app integration with displayer module
  Example/Base.lproj/Main.storyboard
  Example/DisplayController.swift
  Example/ViewController.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Progress+UIViewController.swift
Labels: feature-request

#24 AllowFileAccessFromFileURLs and few enhancements in sample app
  Example/DisplayController.swift
  Example/ViewController.swift
  MiniApp/Classes/Display/MiniAppWebView.swift
  MiniApp/Progress+UIViewController.swift
Labels: Enhancement

#27 Enhancement/sample app display
  Example/Base.lproj/Main.storyboard
  Example/DisplayController.swift
Labels: Enhancement

#28 Updated API endpoints and specs
  Example/Base.lproj/Main.storyboard
  Example/DisplayController.swift
  Example/ViewController.swift
  MiniApp/Classes/MiniAppDownloader.swift
  MiniApp/Classes/Models/ManifestResponse.swift
  MiniApp/Classes/Models/MiniAppInfo.swift
  Tests/Unit/ManifestDownloaderTests.swift
  Tests/Unit/MiniAppDownloaderTests.swift
  Tests/Unit/MiniAppListerTests.swift
Labels: feature-request

#31 Saving download status of mini app using userdefaults
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/MiniAppDownloader.swift
  MiniApp/Classes/RealMiniApp.swift
  MiniApp/Classes/Storage/MiniAppStatus.swift
  MiniApp/Classes/Storage/MiniAppStorage.swift
  Tests/Unit/MiniAppDownloaderTests.swift
  Tests/Unit/MiniAppStatusTests.swift
Labels: feature-request
