Repository rakutentech/ios-miniapp, pull requests merged in 2020-03, with the labels that each got.

#33 Refactoring download mini app operation
  MiniApp/Classes/DownloadOperation.swift
  MiniApp/Classes/Extensions/MiniApp+FileManager.swift
  MiniApp/Classes/MiniAppClient.swift
  MiniApp/Classes/MiniAppDownloader.swift
  MiniApp/Classes/Protocols/MiniAppDownloaderProtocol.swift
  MiniApp/Classes/RealMiniApp.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppDownloaderTests.swift
Labels: Refactoring

#34 UI to test MiniApp info fetch by ID
  Example/Base.lproj/Main.storyboard
  Example/ViewController.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Progress+UIViewController.swift
  MiniApp/en.lproj/Localizable.strings
Labels: feature-request

#36 Updated iOS supporting version to 11.0
  MiniApp.podspec
  MiniApp.xcodeproj/project.pbxproj
  Podfile
Labels: Enhancement

#35 Change App ID and Subscription Key at runtime
  Example/Base.lproj/Main.storyboard
  Example/Config.swift
  Example/DisplayController.swift
  Example/SettingsTableViewController.swift
  Example/ViewController.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Environment.swift
  MiniApp/Classes/MiniApp.swift
  MiniApp/Classes/MiniAppClient.swift
  MiniApp/Classes/MiniAppSdkConfig.swift
  MiniApp/Classes/RealMiniApp.swift
  MiniApp/Progress+UIViewController.swift
  MiniApp/en.lproj/Localizable.strings
  Podfile.lock
  Tests/Unit/MiniAppClientTests.swift
  Tests/Unit/MiniAppDownloaderTests.swift
Labels: feature-request

#39 Updated code coverage percentage to 70
  Dangerfile
Labels: Enhancement

#40 Setting UI changes - Updated Spacing between table cells
  Example/Base.lproj/Main.storyboard
Labels: Enhancement

#38 Refactor - Removed logger class and updated few testcases
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Environment.swift
  MiniApp/Classes/MiniAppLogger.swift
  Tests/Unit/UrlParserTests.swift
Labels: Refactoring

#37 Delete files for old versions
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Extensions/MiniApp+FileManager.swift
  MiniApp/Classes/MiniAppDownloader.swift
  MiniApp/Classes/MiniAppLogger.swift
  MiniApp/Classes/RealMiniApp.swift
  MiniApp/Classes/Storage/MiniAppStatus.swift
  MiniApp/Classes/Storage/MiniAppStorage.swift
  MiniApp/Classes/Utilities/ResponseDecoder.swift
  MiniApp/Classes/Utilities/UrlParser.swift
  Tests/Unit/MiniAppDownloaderTests.swift
  Tests/Unit/MiniAppStatusTests.swift
Labels: feature-request

#41 Refactor/update endpoints change
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/MiniAppDownloader.swift
  MiniApp/Classes/Utilities/UrlParser.swift
  Tests/Unit/MiniAppDownloaderTests.swift
  Tests/Unit/UrlParserTests.swift
Labels: Refactoring

#42 Feature/data separation
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/Displayer.swift
  MiniApp/Classes/Display/MiniAppView.swift
  MiniApp/Classes/Display/MiniAppWebView.swift
  MiniApp/Classes/Display/RealMiniAppView.swift
  MiniApp/Classes/Display/URLSchemeHandler.swift
  MiniApp/Classes/Extensions/MiniApp+FileManager.swift
  MiniApp/Classes/RealMiniApp.swift
  MiniApp/Classes/Utilities/Constants.swift
  Tests/Unit/DisplayerTests.swift
  Tests/Unit/MiniAppViewTests.swift
  Tests/Unit/RealMiniAppViewTests.swift
  Tests/Unit/URLSchemeHandlerTests.swift
Labels: feature-request

#43 Replaced SF symbols as custom images
  Example/Base.lproj/Main.storyboard
  Example/Images.xcassets/Settings.imageset/Contents.json
  Example/Images.xcassets/Settings.imageset/SF_gear.png
  Example/Images.xcassets/Settings.imageset/SF_gear@2x.png
  Example/Images.xcassets/Settings.imageset/SF_gear@3x.png
  Example/Images.xcassets/app-list.imageset/Contents.json
  Example/Images.xcassets/app-list.imageset/SF_list_dash.png
  Example/Images.xcassets/app-list.imageset/SF_list_dash@2x.png
  Example/Images.xcassets/app-list.imageset/SF_list_dash@3x.png
Labels: Enhancement
