Repository rakutentech/ios-miniapp, pull requests merged in 2020-09, with the labels that each got.

#129 Feat/custom permissions interface
  CHANGELOG.md
  Example/AppDelegate.swift
  Example/Base.lproj/Main.storyboard
  Example/CustomPermissionsTableViewController.swift
  Example/UIViewController+MiniApp.swift
  Example/ViewController+MiniAppMessageProtocol.swift
  Example/ViewController.swift
  Example/en.lproj/Localizable.strings
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/RealMiniAppView.swift
  MiniApp/Classes/Extensions/MiniApp+WKUserContentController.swift
  MiniApp/Classes/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/JavascriptBridge/MiniAppJavaScriptPermissionManager.swift
  MiniApp/Classes/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/JavascriptBridge/bridge.js
  MiniApp/Classes/MiniApp.swift
  MiniApp/Classes/Models/MiniAppJavaScriptMessageInfo.swift
  MiniApp/Classes/Models/MiniAppJavascriptErrorInfo.swift
  MiniApp/Classes/Protocols/MiniAppMessageProtocol.swift
  MiniApp/Classes/RealMiniApp.swift
  MiniApp/Classes/Storage/MiniAppKeyChain.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppJavascriptEnumerationTests.swift
  Tests/Unit/MiniAppJavascriptErrorInfoTests.swift
  Tests/Unit/MiniAppKeyChainTests.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/MiniAppStatusTests.swift
  Tests/Unit/MiniAppTests.swift
  Tests/Unit/RealMiniAppTests.swift
  USERGUIDE.md
Labels: feature-request

#130 Updated documentation for public class/variables and some formatting
  MiniApp/Classes/Display/MimeTypes.swift
  MiniApp/Classes/Extensions/MiniApp+FileManager.swift
  MiniApp/Classes/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/MiniAppSdkConfig.swift
Labels: documentation

#131 Persist contact list for sample app
  Example/UserProfile/ContactsListSettingsTableViewController.swift
  Example/UserProfile/UserProfileModel.swift
  Example/UserProfile/UserSettingsTableViewController.swift
  MiniApp.xcodeproj/project.pbxproj
Labels: sample-app

#138 Fix for Custom permissions override at Keychain
  MiniApp/Classes/Storage/MiniAppKeyChain.swift
  Tests/Unit/MiniAppKeyChainTests.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
Labels: Enhancement, Refactoring

#140 Feature/mini 1409
  MiniApp/Classes/MiniAppDownloader.swift
  MiniApp/Classes/Utilities/UrlParser.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppDownloaderTests.swift
  Tests/Unit/UrlParserTests.swift
Labels: Enhancement

#144 Fix/Mini-1694, 1771
  Example/Controllers/UserSettingsTableViewController.swift
  MiniApp/Classes/Storage/MiniAppStatus.swift
Labels: Refactoring, bug-fix, sample-app
