Repository rakutentech/ios-miniapp, pull requests merged in 2020-10, with the labels that each got.

#146 Update script to set only Bundle Version
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Example/Controllers/UserSettingsTableViewController.swift
  MiniApp.xcodeproj/project.pbxproj
Labels: Refactoring, sample-app

#149 Retrieve User name and profile photo
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+MiniAppUserInfoProtocol.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/Displayer.swift
  MiniApp/Classes/Display/RealMiniAppView.swift
  MiniApp/Classes/Extensions/MiniApp+WKUserContentController.swift
  MiniApp/Classes/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/MiniApp.swift
  MiniApp/Classes/Protocols/MiniAppMessageProtocol.swift
  MiniApp/Classes/Protocols/MiniAppUserInfoDelegate.swift
  MiniApp/Classes/RealMiniApp.swift
  Podfile.lock
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/RealMiniAppViewTests.swift
  USERGUIDE.md
Labels: feature-request

#152 Feat/mini 1828 tel support
  MiniApp.xcodeproj/project.pbxproj
  MiniApp.xcodeproj/xcshareddata/xcschemes/MiniApp-Example.xcscheme
  MiniApp.xcodeproj/xcshareddata/xcschemes/MiniApp_Tests.xcscheme
  MiniApp/Classes/Utilities/MiniAppExternalUrlLoader.swift
  Tests/Unit/MiniAppExternalUrlLoaderTests.swift
Labels: SDK, feature-request

#153 Feature/mini 1833 - _blank target links opening
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/ExternalWebViewController.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/MiniAppExternalWebViewController.swift
  MiniApp/Classes/Display/MiniAppNavigationBar.swift
  MiniApp/Classes/Display/MiniAppNavigationConfig.swift
  MiniApp/Classes/Extensions/UIWindow+MiniApp.swift
  MiniApp/Classes/Utilities/MiniAppExternalUrlLoader.swift
Labels: Enhancement, Refactoring, SDK, bug-fix

#151 Migrate sharing controller from demo app to SDK
  Example/Controllers/Extensions/ViewController+MiniAppMessageProtocol.swift
  MiniApp/Classes/Display/Displayer.swift
  MiniApp/Classes/Display/RealMiniAppView.swift
  MiniApp/Classes/Extensions/MiniApp+WKUserContentController.swift
  MiniApp/Classes/Extensions/UIViewController+MiniApp.swift
  MiniApp/Classes/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/MiniApp.swift
  MiniApp/Classes/Protocols/MiniAppMessageDelegate.swift
  MiniApp/Classes/Protocols/MiniAppShareContentDelegate.swift
  MiniApp/Classes/RealMiniApp.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  USERGUIDE.md
Labels: Enhancement, Refactoring, documentation, sample-app

#154 Feature/mini 287
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Example/Controllers/ViewController.swift
  Example/Utils/UIImageView+Extensions.swift
Labels: Enhancement, feature-request, sample-app

#155 Update properties to enable media playback require user action
  MiniApp/Classes/Display/MiniAppWebView.swift
Labels: SDK, feature-request

#156 Fix for the memory leak
  MiniApp/Classes/Display/MiniAppExternalWebViewController.swift
  MiniApp/Classes/Utilities/MiniAppExternalUrlLoader.swift
Labels: SDK, bug-fix
