Repository rakutentech/ios-miniapp, pull requests merged in 2021-06, with the labels that each got.

#277 [MINI-3128] Refactored Access token error handling
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/core/JavascriptBridge/MAJavascriptErrorHandler.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/core/Models/MiniAppJavascriptErrorInfo.swift
  MiniApp/Classes/core/Protocols/MiniAppMessageDelegate.swift
  Podfile.lock
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/MiniAppViewControllerTests.swift
Labels: Refactoring, SDK

#282 Updated RegEx
  Example/Utils/String+MiniApp.swift
Labels: Refactoring, sample-app

#280 added QA settings screen
  CHANGELOG.md
  Example/Assets/Images.xcassets/exam.imageset/Contents.json
  Example/Assets/Images.xcassets/exam.imageset/exam.svg
  Example/Controllers/Extensions/ViewController+MiniAppUserInfoProtocol.swift
  Example/Controllers/QASettingsTableViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Settings.storyboard
  MiniApp.xcodeproj/project.pbxproj
  Podfile.lock
Labels: Refactoring, sample-app

#281 [MINI-3142] Support Multiple RAT Accounts
  CHANGELOG.md
  MiniApp/Classes/core/Display/Displayer.swift
  MiniApp/Classes/core/Display/RealMiniAppView.swift
  MiniApp/Classes/core/Extensions/NotificationCenter+RAT.swift
  MiniApp/Classes/core/MiniAppAnalytics.swift
  MiniApp/Classes/core/MiniAppSdkConfig.swift
  MiniApp/Classes/core/Models/MAAnalyticsConfig.swift
  MiniApp/Classes/core/RealMiniApp.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppSdkConfigTests.swift
Labels: Refactoring, SDK

#287 Adding support .formSubmitted for redirection
  MiniApp/Classes/core/Display/MiniAppExternalWebViewController.swift
Labels: SDK, bug-fix

#289 Fix/mini 3402 contacts
  Example/Controllers/ContactsListSettingsTableViewController.swift
Labels: bug-fix, sample-app

#291 [MINI-3399] - Fix codebase latest manifest issue
  MiniApp/Classes/core/Downloader/MetaDataDownloader.swift
  MiniApp/Classes/core/RealMiniApp.swift
Labels: SDK, bug-fix
