Repository rakutentech/ios-miniapp, pull requests merged in 2021-04, with the labels that each got.

#253 Caching MiniAppManifest response
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/core/Downloader/DownloadOperation.swift
  MiniApp/Classes/core/Downloader/ManifestDownloader.swift
  MiniApp/Classes/core/Downloader/MetaDataDownloader.swift
  MiniApp/Classes/core/Downloader/MiniAppClient.swift
  MiniApp/Classes/core/Downloader/MiniAppDownloader.swift
  MiniApp/Classes/core/Downloader/MiniAppInfoFetcher.swift
  MiniApp/Classes/core/MiniAppInfoFetcher.swift
  MiniApp/Classes/core/RealMiniApp.swift
  MiniApp/Classes/core/Storage/MAManifestCache.swift
  MiniApp/Classes/core/Storage/MiniAppKeyChain.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MetaDataDownloaderTests.swift
  Tests/Unit/MiniAppInfoFetcherTests.swift
Labels: SDK

#255 docs: Add FAQ item about clearing session data
  USERGUIDE.md
Labels: documentation

#256 Localization standardization
  CHANGELOG.md
  Example/Assets/en.lproj/Localizable.strings
  Example/Assets/ja.lproj/Localizable.strings
  Example/Controllers/ContactsListSettingsTableViewController.swift
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/Extensions/ViewController+MiniAppMessageProtocol.swift
  Example/Controllers/SettingsTableViewController.swift
  Example/Controllers/ViewController.swift
  Example/Utils/Progress+UIViewController.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/admob/AdMobDisplayer.swift
  MiniApp/Classes/admob7/AdMobDisplayer.swift
  MiniApp/Classes/core/Display/ViewControllers/Custom Permissions/CustomPermissionsRequestViewController.swift
  MiniApp/Classes/core/Display/ViewControllers/Custom Permissions/CustomPermissionsRequestViewController.xib
  MiniApp/Classes/core/Extensions/NSError+MiniApp.swift
  MiniApp/Classes/core/Extensions/RealMiniAppView+WKUIDelegate.swift
  MiniApp/Classes/core/Extensions/Storyboard.swift
  MiniApp/Classes/core/MASDKError.swift
  MiniApp/Classes/core/Protocols/MiniAppUserInfoDelegate.swift
  MiniApp/Classes/core/Utilities/MASDKLocale.swift
  MiniApp/en.lproj/Localizable.strings
  MiniApp/ja.lproj/Localizable.strings
  Tests/Unit/MASDKErrorTests.swift
  Tests/Unit/MiniApp+StringTests.swift
  USERGUIDE.md
Labels: Enhancement, Refactoring, SDK, sample-app
