Repository rakutentech/ios-miniapp, pull requests merged in 2021-08, with the labels that each got.

#311 Fix for GitHub action swiftlint
  .github/workflows/swiftlint.yml
Labels: scripts

#313 Fix/mini 3853 permissions
  MiniApp/Classes/core/RealMiniApp.swift
  MiniApp/Classes/core/Storage/MiniAppStatus.swift
  Podfile.lock
Labels: SDK

#310 Refactor/release candidate script
  scripts/release-candidate.sh
Labels: Refactoring

#309 [MINI-3351] - Feat/mini 3351 back forward nav
  Example/Controllers/DisplayController.swift
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/ViewController.swift
  MiniApp/Classes/core/Display/MiniAppNavigationConfig.swift
  MiniApp/Classes/core/Display/RealMiniAppView.swift
Labels: SDK, feature-request

#285 MiniAppUI launch integration for demo app
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/ViewController.swift
  MiniApp/Classes/ui/MiniAppUI.swift
  MiniApp/Classes/ui/MiniAppViewController.swift
Labels: Enhancement, bug-fix, SDK

#302 [MINI-3294] Deep linking Error Screens
  Example/Assets/Colors.xcassets/ActionBlue.colorset/Contents.json
  Example/Assets/Images.xcassets/QR-Error-Type1.imageset/Contents.json
  Example/Assets/Images.xcassets/QR-Error-Type1.imageset/QR-Error-Type1.svg
  Example/Assets/Images.xcassets/QR-Error-Type2.imageset/Contents.json
  Example/Assets/Images.xcassets/QR-Error-Type2.imageset/QR-Error-Type2.svg
  Example/Assets/en.lproj/Localizable.strings
  Example/Controllers/Deeplink/DeeplinkErrorViewController.swift
  Example/Controllers/Storyboards/Deeplink.storyboard
  Example/Utils/UIColor+MiniApp.swift
  Example/Utils/UITextView+MiniApp.swift
  MiniApp.xcodeproj/project.pbxproj
Labels: feature-request, sample-app

#295 [MINI-2946][MINI-2948] Manifest stored as a JSON file + hash checking
  CHANGELOG.md
  Example/Controllers/CustomPermissionsListViewController.swift
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/MAFirstLaunchController.swift
  Example/Controllers/SettingsTableViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Example/Controllers/UserSettingsTableViewController.swift
  Example/Controllers/ViewController.swift
  Example/Models/UserProfileModel.swift
  Example/Utils/Encodable+MiniApp.swift
  Example/Utils/ImageCache.swift
  Example/Utils/Print+MiniApp.swift
  Example/Utils/String+MiniApp.swift
  Example/Utils/UIView+MiniApp.swift
  Example/Utils/UIViewController+MiniApp.swift
  MiniApp.podspec
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/core/Display/MiniAppNavigationConfig.swift
  MiniApp/Classes/core/Downloader/MetaDataDownloader.swift
  MiniApp/Classes/core/Environment.swift
  MiniApp/Classes/core/Extensions/Bundle+Environment.swift
  MiniApp/Classes/core/Extensions/FileManager+MiniApp.swift
  MiniApp/Classes/core/Extensions/Int+MiniApp.swift
  MiniApp/Classes/core/Extensions/String+MiniApp.swift
  MiniApp/Classes/core/JavascriptBridge/Chat/ChatMessageBridgeDelegate.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppJavaScriptPermissionManager.swift
  MiniApp/Classes/core/MiniAppAnalytics.swift
  MiniApp/Classes/core/MiniAppLogger.swift
  MiniApp/Classes/core/Models/MiniAppManifest.swift
  MiniApp/Classes/core/Protocols/MiniAppAdDisplayDelegate.swift
  MiniApp/Classes/core/Protocols/MiniAppDisplayProtocol.swift
  MiniApp/Classes/core/Protocols/MiniAppDownloaderProtocol.swift
  MiniApp/Classes/core/Protocols/MiniAppShareContentDelegate.swift
  MiniApp/Classes/core/Protocols/MiniAppUserInfoDelegate.swift
  MiniApp/Classes/core/RealMiniApp.swift
  MiniApp/Classes/core/Storage/MAManifestCache.swift
  MiniApp/Classes/core/Storage/MAManifestStorage.swift
  MiniApp/Classes/core/Storage/MiniAppKeyChain.swift
  MiniApp/Classes/core/Storage/MiniAppPermissionsStorage.swift
  MiniApp/Classes/core/Storage/MiniAppStatus.swift
  MiniApp/Classes/core/Storage/MiniAppStorage.swift
  MiniApp/Classes/core/Storage/MiniAppVerificationStorage.swift
  MiniApp/Classes/core/Storage/MiniAppVersion.swift
  MiniApp/Classes/ui/MiniAppViewController.swift
  Podfile.lock
  Tests/Unit/Helpers.swift
Labels: feature-request, Refactoring, Enhancement, SDK

#318 Updated delegates in Sample app
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  MiniApp/Classes/core/Display/RealMiniAppView.swift
  Podfile.lock
Labels: sample-app

#315 Refactor/increase test coverage
  .codecov.yml
  Tests/Unit/Helpers.swift
  Tests/Unit/MessageInterfaceExtensionTests.swift
  Tests/Unit/MiniAppJavascriptErrorInfoTests.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/MiniAppTests.swift
Labels: Refactoring, SDK

#316 [MINI-3118] SDK Fix for Required permission validation
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/ViewController.swift
  Example/Utils/Progress+UIViewController.swift
  MiniApp/Classes/core/Downloader/MetaDataDownloader.swift
  MiniApp/Classes/core/Extensions/NSError+MiniApp.swift
  MiniApp/Classes/core/RealMiniApp.swift
Labels: bug-fix, SDK

#320 Updated code to support Enable/Disable Nav buttons in MiniAppUI
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  MiniApp/Classes/ui/MiniAppUI.swift
  MiniApp/Classes/ui/MiniAppViewController.swift
Labels: sample-app, SDK

#323 Disable navigation buttons at initial launch.
  MiniApp/Classes/ui/MiniAppViewController.swift
Labels: SDK

#321 Fix/first time screen
  Example/Controllers/Extensions/ViewController+MiniApp.swift
Labels: bug-fix, sample-app

#322 [MINI-2673] - Changes to sync with navigator default error response
  MiniApp/Classes/core/JavascriptBridge/MAJavascriptErrorHandler.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/core/Models/MiniAppJavascriptErrorInfo.swift
Labels: Refactoring, SDK

#324 [MINI-1746] Add profile settings image remove button
  Example/Controllers/Storyboards/Base.lproj/Settings.storyboard
  Example/Controllers/UserSettingsTableViewController.swift
Labels: feature-request, sample-app
