Repository rakutentech/ios-miniapp, pull requests merged in 2021-10, with the labels that each got.

#332 [MALI-602] Expose Link / Host Version to the MiniApp
  MiniApp/Classes/core/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/core/Protocols/MiniAppMessageDelegate.swift
  MiniApp/Classes/core/RealMiniApp.swift
  MiniApp/Classes/core/Utilities/MASDKLocale.swift
  MiniApp/en.lproj/Localizable.strings
Labels: feature-request, MALI, ✓

#335 [FIX] MiniApp SDK does not compile when Signature is not in podfile
  MiniApp/Classes/core/Downloader/MiniAppClient.swift
Labels: ✓

#336 [MINI-4142] Launch mini app using QR even if application is not in foreground.
  CHANGELOG.md
  Example/AppDelegate.swift
Labels: Refactoring, ✓

#338 Fix for MINI-4165
  MiniApp/Classes/core/MASDKError.swift
Labels: bug-fix, ✓
