Repository rakutentech/ios-miniapp, pull requests merged in 2021-02, with the labels that each got.

#210 Added first time launch request from Host app
  Example/Controllers/MAFirstLaunchController.swift
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Example/Controllers/ViewController.swift
  Example/Models/UserProfileModel.swift
  Example/Utils/UIView+MiniApp.swift
  MiniApp.xcodeproj/project.pbxproj
Labels: SDK, feature-request

#213 Release 2.8.0
  CHANGELOG.md
  MiniApp.podspec
  MiniApp.xcodeproj/project.pbxproj
  MiniApp.xcodeproj/xcshareddata/xcschemes/MiniApp-Example.xcscheme
  MiniApp/Classes/core/Extensions/NSError+MiniApp.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  Podfile
  Podfile.lock
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/RealMiniAppViewTests.swift
  scripts/configure-secrets.sh
Labels: RELEASE

#215 Bugfix/mini 2635
  Example/Controllers/ViewController.swift
Labels: Enhancement, bug-fix, sample-app

#214 Fix on wording
  MiniApp/Classes/admob/AdMobDisplayer.swift
  MiniApp/Classes/admob7/AdMobDisplayer.swift
  Podfile.lock
Labels: SDK, wording

#216 Appcenter integration
  Example/AppDelegate.swift
  Example/Info.plist
  MiniApp.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
Labels: Enhancement, sample-app

#218 Removes all unnecessary toEventually tests
  Tests/Unit/DisplayerTests.swift
  Tests/Unit/ListingAPITests.swift
  Tests/Unit/ManifestAPITests.swift
  Tests/Unit/MimeTypesTests.swift
  Tests/Unit/MiniApp+NSErrorTests.swift
  Tests/Unit/MiniApp+StringTests.swift
  Tests/Unit/MiniApp+URLRequestTests.swift
  Tests/Unit/MiniAppExternalUrlLoaderTests.swift
  Tests/Unit/MiniAppJavascriptEnumerationTests.swift
  Tests/Unit/MiniAppJavascriptErrorInfoTests.swift
  Tests/Unit/MiniAppKeyChainTests.swift
  Tests/Unit/MiniAppStatusTests.swift
  Tests/Unit/MiniAppTests.swift
  Tests/Unit/RealMiniAppTests+Permissions.swift
  Tests/Unit/RealMiniAppTests.swift
  Tests/Unit/RealMiniAppViewTests.swift
  Tests/Unit/URLSchemeHandlerTests.swift
  Tests/Unit/UrlParserTests.swift
Labels: UT

#217 🚧 removed all deprecations 🚧
  CHANGELOG.md
  Example/Controllers/DisplayController.swift
  Example/Controllers/DisplayNavigationController.swift
  Example/Controllers/ViewController.swift
  Example/Utils/Config.swift
  MiniApp/Classes/core/Display/Displayer.swift
  MiniApp/Classes/core/Display/RealMiniAppView.swift
  MiniApp/Classes/core/Environment.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/core/MiniApp.swift
  MiniApp/Classes/core/MiniAppClient.swift
  MiniApp/Classes/core/MiniAppSdkConfig.swift
  MiniApp/Classes/core/Protocols/MiniAppDisplayProtocol.swift
  MiniApp/Classes/core/Protocols/MiniAppMessageDelegate.swift
  MiniApp/Classes/core/Protocols/MiniAppUserInfoDelegate.swift
  MiniApp/Classes/core/RealMiniApp.swift
  Podfile.lock
  Tests/Unit/EnvironmentTests.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MessageInterfaceExtensionTests.swift
  Tests/Unit/MiniAppClientTests.swift
  Tests/Unit/MiniAppSdkConfigTests.swift
  Tests/Unit/RealMiniAppTests.swift
Labels: Enhancement, Refactoring, SDK

#219 🚧🚧 upgraded minimum deployment version to iOS 13.0 🚧🚧
  CHANGELOG.md
  Example/AppDelegate.swift
  Example/Utils/Progress+UIViewController.swift
  Example/Utils/UIViewController+MiniApp.swift
  MiniApp.podspec
  MiniApp.xcodeproj/project.pbxproj
  MiniApp.xcodeproj/xcshareddata/xcschemes/MiniApp Sample debug.xcscheme
  MiniApp.xcodeproj/xcshareddata/xcschemes/MiniApp Sample release.xcscheme
  MiniApp.xcodeproj/xcshareddata/xcschemes/MiniApp-Example.xcscheme
  MiniApp.xcodeproj/xcshareddata/xcschemes/MiniApp_Tests.xcscheme
  MiniApp/Classes/core/Extensions/UIApplication.swift
  MiniApp/Classes/core/Storage/MiniAppKeyChain.swift
  Podfile
  Podfile.lock
  USERGUIDE.md
  fastlane/Fastfile
  scripts/deploy-to-app-center.sh
Labels: Enhancement, SDK

#223 check parameters
  Example/Controllers/Settings/QueryParamViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Example/Controllers/Storyboards/Settings.storyboard
  MiniApp.xcodeproj/project.pbxproj
  Podfile.lock
Labels: Enhancement, Refactoring, feature-request, sample-app

#224 fix constraints producing warnings and bad logs at runtime
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Example/Controllers/Storyboards/Settings.storyboard
  MiniApp/Classes/core/Display/ViewControllers/Custom Permissions/MACustomPermissionCell.xib
Labels: SDK, bug-fix, sample-app
