Repository rakutentech/ios-miniapp, pull requests merged in 2021-11, with the labels that each got.

#348 [MINI-4195] File Download Improvement
  Example/Controllers/Extensions/ViewController+MiniApp.swift
Labels: sample-app

#350 File download issue fix
  Example/Controllers/Extensions/ViewController+MiniApp.swift
Labels: sample-app

#351 [MINI-4334] - Sample app crash fix - Added Photos permission
  CHANGELOG.md
  Example/Info.plist
Labels: bug-fix, sample-app

#329 [MINI-3848] Demo app analytics
  Example/Analytics/DemoAppAnalytics.swift
  Example/Analytics/NotificationCenter+RAT.swift
  Example/Analytics/RATController.swift
  Example/Analytics/Swizzling.swift
  Example/AppDelegate.swift
  Example/Assets/en.lproj/Localizable.strings
  Example/Controllers/ChatContactsSelectorViewController.swift
  Example/Controllers/CustomPermissionsListViewController.swift
  Example/Controllers/Deeplink/DeeplinkErrorViewController.swift
  Example/Controllers/DisplayController.swift
  Example/Controllers/FirstLaunchViewController.swift
  Example/Controllers/MAFirstLaunchController.swift
  Example/Controllers/Settings/AccessTokenViewController.swift
  Example/Controllers/Settings/ContactsListSettingsTableViewController.swift
  Example/Controllers/Settings/ManageCustomPermissionsViewController.swift
  Example/Controllers/Settings/PointsSettingsTableViewController.swift
  Example/Controllers/Settings/QASettingsTableViewController.swift
  Example/Controllers/Settings/QueryParamViewController.swift
  Example/Controllers/Settings/SettingsTableViewController.swift
  Example/Controllers/Settings/UserSettingsTableViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Example/Controllers/Storyboards/Base.lproj/Settings.storyboard
  Example/Controllers/ViewController.swift
  Example/Utils/String+MiniApp.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/core/Models/MAAnalyticsConfig.swift
  Podfile.lock
Labels: feature-request, sample-app, ✓

#353 Refactor/code coverage
  .codecov.yml
  CHANGELOG.md
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/core/Downloader/MetaDataDownloader.swift
  MiniApp/Classes/core/Extensions/FileManager+MiniApp.swift
  MiniApp/Classes/core/Storage/MiniAppCacheVerifier.swift
  MiniApp/Classes/core/Storage/MiniAppVersion.swift
  Podfile.lock
  Tests/Unit/EnvironmentTests.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppClientTests.swift
  Tests/Unit/Signature/VerifierTests.swift
  Tests/Unit/core/Downloader/MetaDataDownloaderTests.swift
  Tests/Unit/core/MiniAppVersionTests.swift
Labels: Refactoring, SDK, UT

#354 [MINI-1746] Remove Profile Image Fix
  Example/Assets/en.lproj/Localizable.strings
  Example/Assets/ja.lproj/Localizable.strings
  Example/Controllers/Settings/UserSettingsTableViewController.swift
  MiniApp/Classes/core/Utilities/MASDKLocale.swift
Labels: bug

#355 [MINI-3848] Updated Demo app analytics
  Example/Analytics/DemoAppAnalytics.swift
  Example/Analytics/NotificationCenter+RAT.swift
  Example/Analytics/RATController.swift
  Example/Analytics/RATNotificationCenter.swift
  Example/Assets/en.lproj/Localizable.strings
  Example/Controllers/Settings/AccessTokenViewController.swift
  Example/Controllers/Settings/CustomPermissionsListViewController.swift
  Example/Controllers/Settings/DeeplinkListViewController.swift
  Example/Controllers/Settings/GeneralTableViewController.swift
  Example/Controllers/Settings/ManageCustomPermissionsViewController.swift
  Example/Controllers/Settings/SettingsTableViewController.swift
  Example/Controllers/Settings/SignatureSettingsTableViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Settings.storyboard
  MiniApp.xcodeproj/project.pbxproj
Labels: Refactoring, sample-app

#356 [MINI-4369] Switch Staging & Production Environment
  .github/workflows/fastlane.yml
  CHANGELOG.md
  DEV.md
  Example/Controllers/FirstLaunchViewController.swift
  Example/Controllers/Settings/SettingsTableViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Settings.storyboard
  Example/Info.plist
  Example/Utils/Config.swift
  Podfile
Labels: feature-request, sample-app

#357 Manifest Localization changes
  CHANGELOG.md
  Example/Controllers/ViewController.swift
  MiniApp/Classes/core/API/MetaDataAPI.swift
  MiniApp/Classes/core/Downloader/MetaDataDownloader.swift
  MiniApp/Classes/core/Downloader/MiniAppClient.swift
  MiniApp/Classes/core/MiniApp.swift
  MiniApp/Classes/core/RealMiniApp.swift
  MiniApp/ja.lproj/Localizable.strings
  Podfile.lock
  Tests/Unit/Helpers.swift
  Tests/Unit/MetaDataAPITests.swift
  Tests/Unit/MiniAppTests.swift
  Tests/Unit/core/Downloader/MetaDataDownloaderTests.swift
  USERGUIDE.md
Labels: feature-request, SDK
