Repository rakutentech/ios-miniapp, pull requests merged in 2021-12, with the labels that each got.

#358 [MINI-4414] Default locale from host app
  Example/Assets/en.lproj/Localizable.strings
  Example/Assets/ja.lproj/Localizable.strings
  Example/Controllers/Extensions/ViewController+MiniAppMessageProtocol.swift
  MiniApp/Classes/core/Extensions/String+MiniApp.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/core/Protocols/MiniAppMessageDelegate.swift
  MiniApp/Classes/core/RealMiniApp.swift
  MiniApp/en.lproj/Localizable.strings
  MiniApp/ja.lproj/Localizable.strings
  Tests/Unit/Helpers.swift
  Tests/Unit/MessageInterfaceExtensionTests.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
Labels: feature-request, Refactoring

#361 [MINI-4419] Promotional image and text
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  MiniApp/Classes/core/Models/MiniAppInfo.swift
  MiniApp/Classes/ui/MiniAppSharePreviewViewController.swift
  MiniApp/Classes/ui/MiniAppUI.swift
  MiniApp/Classes/ui/MiniAppViewController.swift
Labels: feature-request, sample-app

#364 Changelog update
  CHANGELOG.md
Labels: documentation

#366 [MINI-4335] Error message display for missing name and email + file download success alert
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/Settings/ContactsListSettingsTableViewController.swift
Labels: bug, Enhancement

#367 [MINI-4355] contact fields name / email fix
  Example/Controllers/Settings/ContactsListSettingsTableViewController.swift
Labels: bug-fix
