Repository rakutentech/ios-miniapp, pull requests merged in 2021-05, with the labels that each got.

#258 Convert getUniqueId to be asynchronous
  Example/Controllers/Extensions/ViewController+MiniAppMessageProtocol.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/core/Protocols/MiniAppMessageDelegate.swift
  MiniApp/Classes/core/RealMiniApp.swift
  Podfile.lock
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/RealMiniAppTests.swift
  USERGUIDE.md
Labels: Refactoring, SDK

#260 Added support for mailto
  CHANGELOG.md
  MiniApp/Classes/core/Display/RealMiniAppView.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/core/Utilities/MiniAppExternalUrlLoader.swift
Labels: SDK, feature-request

#259 Added Custom permission to send message
  CHANGELOG.md
  MiniApp/Classes/core/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
Labels: SDK, feature-request

#266 Feature/mini 3108
  Example/AppDelegate.swift
  Example/Assets/Colors.xcassets/Crimson.colorset/Contents.json
  Example/Controllers/ChatContactsSelectorViewController.swift
  Example/Controllers/ContactsListSettingsTableViewController.swift
  Example/Controllers/Extensions/ViewController+ChatDelegate.swift
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Example/Controllers/ViewController.swift
  Example/Utils/UIView+MiniApp.swift
Labels: Refactoring, feature-request, sample-app

#268 Fixed localization and updated Changelog
  CHANGELOG.md
  MiniApp/Classes/core/Display/ViewControllers/Custom Permissions/CustomPermissionsRequestViewController.xib
Labels: Refactoring, SDK

#269 [MINI-3121] disabled caching in preview mode
  MiniApp/Classes/core/Downloader/MiniAppDownloader.swift
  icon.png
Labels: SDK, feature-request

#270 Fix MINI-3237
  MiniApp/Classes/core/Display/ViewControllers/Custom Permissions/CustomPermissionsRequestViewController.swift
Labels: SDK

#249 Mali 109 miniapp display UI
  MiniApp.podspec
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/core/Assets/MiniApp.xcassets/error_bubble.imageset/Contents.json
  MiniApp/Classes/core/Assets/MiniApp.xcassets/error_bubble.imageset/newsErrorPageNoticeIcon.pdf
  MiniApp/Classes/core/Utilities/MASDKLocale.swift
  MiniApp/Classes/ui/MiniAppUI.swift
  MiniApp/Classes/ui/MiniAppViewController+Fallback.swift
  MiniApp/Classes/ui/MiniAppViewController+ViewState.swift
  MiniApp/Classes/ui/MiniAppViewController.swift
  MiniApp/en.lproj/Localizable.strings
  Podfile
  Podfile.lock
  Tests/Unit/MiniAppViewControllerTests.swift
Labels: MALI, SDK, feature-request, good first issue, sample-app

#271 Update getAccessToken to support new error types
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+MiniAppUserInfoProtocol.swift
  MiniApp/Classes/core/Protocols/MiniAppMessageDelegate.swift
  MiniApp/Classes/core/Protocols/MiniAppUserInfoDelegate.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
Labels: Refactoring, SDK

#276 Set default mode to be Publishing mode
  MiniApp/Classes/core/Downloader/MiniAppClient.swift
  MiniApp/Classes/core/MiniAppSdkConfig.swift
  Tests/Unit/MiniAppClientTests.swift
  Tests/Unit/MiniAppSdkConfigTests.swift
Labels: Refactoring, SDK

#275 Candidate
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  MiniApp.podspec
  MiniApp/Classes/admob7/AdMobDisplayer.swift
  MiniApp/Classes/core/Display/ViewControllers/Custom Permissions/CustomPermissionsRequestViewController.swift
  MiniApp/Classes/core/MASDKError.swift
  MiniApp/Classes/core/Utilities/MASDKLocale.swift
  Podfile.lock
  USERGUIDE.md
Labels: RELEASE
