Repository rakutentech/ios-miniapp, pull requests merged in 2021-01, with the labels that each got.

#198 Settings screen icons issue fix
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
Labels: bug-fix, sample-app

#197 Bug fixes for Sample app
  Example/Controllers/ContactsListSettingsTableViewController.swift
  Example/Controllers/Extensions/ViewController+MiniAppUserInfoProtocol.swift
  Example/Controllers/ViewController.swift
Labels: bug-fix, sample-app

#194 Feature: analytics notifications
  CHANGELOG.md
  MiniApp.podspec
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/Displayer.swift
  MiniApp/Classes/Display/RealMiniAppView.swift
  MiniApp/Classes/Extensions/Date+MiniApp.swift
  MiniApp/Classes/Extensions/FileManager+MiniApp.swift
  MiniApp/Classes/Extensions/NSError+MiniApp.swift
  MiniApp/Classes/Extensions/NotificationCenter+RAT.swift
  MiniApp/Classes/Extensions/String+MiniApp.swift
  MiniApp/Classes/Extensions/UIView+MiniApp.swift
  MiniApp/Classes/Extensions/URL+MiniApp.swift
  MiniApp/Classes/Extensions/URLRequest+MiniApp.swift
  MiniApp/Classes/Extensions/WKUserContentController+MiniApp.swift
  MiniApp/Classes/MiniAppAnalytics.swift
  MiniApp/Classes/MiniAppClient.swift
  MiniApp/Classes/MiniAppDownloader.swift
  MiniApp/Classes/MiniAppLogger.swift
  MiniApp/Classes/RealMiniApp.swift
  MiniApp/Classes/Utilities/LoaderObjC.m
  Podfile.lock
  Tests/Unit/DisplayerTests.swift
  Tests/Unit/RealMiniAppViewTests.swift
  USERGUIDE.md
  configure-secrets.sh
Labels: Enhancement, Refactoring, SDK, feature-request

#199 Feat/query params
  CHANGELOG.md
  Example/Assets/Images.xcassets/questionmark.imageset/Contents.json
  Example/Assets/Images.xcassets/questionmark.imageset/questionmark.png
  Example/Assets/Images.xcassets/questionmark.imageset/questionmark@2x.png
  Example/Assets/Images.xcassets/questionmark.imageset/questionmark@3x.png
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/Settings/QueryParamViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Example/Models/UserProfileModel.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/Display/Displayer.swift
  MiniApp/Classes/Display/MiniAppWebView.swift
  MiniApp/Classes/Display/RealMiniAppView.swift
  MiniApp/Classes/Extensions/String+MiniApp.swift
  MiniApp/Classes/MiniApp.swift
  MiniApp/Classes/RealMiniApp.swift
  Podfile.lock
  Tests/Unit/Helpers.swift
  USERGUIDE.md
Labels: SDK, feature-request, sample-app

#203 URL query param encoding refactor
  MiniApp/Classes/Display/MiniAppWebView.swift
  MiniApp/Classes/Extensions/String+MiniApp.swift
Labels: Refactoring, SDK

#200 Rename protocol `requestPermission` to `requestDevicePermission`
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+MiniAppMessageProtocol.swift
  MiniApp/Classes/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/Protocols/MiniAppMessageDelegate.swift
  MiniApp/Classes/RealMiniApp.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/RealMiniAppTests+Permissions.swift
  USERGUIDE.md
Labels: Enhancement, Refactoring, SDK

#205 Fix for Mini-2408
  Example/Controllers/ViewController.swift
Labels: SDK, bug-fix, sample-app

#206 Remove encoding for all query params
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  MiniApp/Classes/core/Display/MiniAppWebView.swift
  MiniApp/Classes/core/Display/RealMiniAppView.swift
  MiniApp/Classes/core/Extensions/String+MiniApp.swift
Labels: Refactoring, SDK

#212 Candidate: fix GPS location update
  CHANGELOG.md
  MiniApp.xcodeproj/xcshareddata/xcschemes/MiniApp-Example.xcscheme
  MiniApp/Classes/core/Extensions/NSError+MiniApp.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
Labels: Enhancement, bug-fix
