Repository rakutentech/ios-miniapp, pull requests merged in 2021-07, with the labels that each got.

#288 Deep linking support.
  Example/AppDelegate.swift
  Example/Info.plist
Labels: SDK, feature-request

#290 [MINI-3241] Rakuten points implementation
  Example/Controllers/Extensions/ViewController+MiniAppUserInfoProtocol.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  MiniApp/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  MiniApp/Classes/core/Models/MiniAppJavascriptErrorInfo.swift
  MiniApp/Classes/core/Protocols/MiniAppUserInfoDelegate.swift
Labels: MALI, bridge-code, feature-request

#299 [MINI-3451] Addition of a banner message
  CHANGELOG.md
  Example/AppDelegate.swift
  Example/Assets/Images.xcassets/megaphone.imageset/Contents.json
  Example/Assets/Images.xcassets/megaphone.imageset/megaphone.svg
  Example/Controllers/ChatContactsSelectorViewController.swift
  Example/Controllers/ContactsListSettingsTableViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Example/Utils/UIColor+MiniApp.swift
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/core/JavascriptBridge/Chat/MessageToContact.swift
  Podfile.lock
Labels: Enhancement, SDK, sample-app

#298 Feat/GitHub actions swiftlint
  .github/workflows/swiftlint.yml
Labels: feature-request

#303 [MINI-3341] Modified app center script to deploy device builds
  MiniApp.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
  scripts/deploy-to-app-center.sh
Labels: CI

#296 Refactor/code coverage support
  MiniApp/Classes/core/RealMiniApp.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/MiniAppStatusTests.swift
  Tests/Unit/MiniAppTests.swift
Labels: SDK

#304 [MINI-3241] Add Points Settings
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+MiniAppUserInfoProtocol.swift
  Example/Controllers/PointsSettingsTableViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Settings.storyboard
  Example/Models/UserPointsModel.swift
  MiniApp.xcodeproj/project.pbxproj
  USERGUIDE.md
Labels: sample-app

#305 release candidate script
  DEV.md
  scripts/deploy-to-app-center.sh
  scripts/release-candidate.sh
Labels: documentation, scripts

#306 Updated Testcases
  .codecov.yml
  MiniApp.xcodeproj/project.pbxproj
  MiniApp/Classes/core/Display/MiniAppExternalWebViewController.swift
  MiniApp/Classes/core/Display/ViewControllers/Custom Permissions/CustomPermissionsRequestViewController.swift
  Tests/Unit/EnvironmentTests.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MASDKLocaleTests.swift
  Tests/Unit/MessageInterfaceExtensionTests.swift
  Tests/Unit/MiniAppTests.swift
  Tests/Unit/RealMiniAppTests.swift
  Tests/Unit/UIModule/AdMobDisplayerTests.swift
  Tests/Unit/core/Display/CustomPermissionsViewControllerTests.swift
  Tests/Unit/core/Display/MiniAppExternalWebViewControllerTests.swift
Labels: SDK, UT

#307 [MINI-3553] Fix - Points page - sample app changes
  Example/Controllers/PointsSettingsTableViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Settings.storyboard
Labels: bug-fix, sample-app

#308 Storyboard fix
  Example/Controllers/Storyboards/Base.lproj/Settings.storyboard
Labels: bug-fix, sample-app

#312 Fix/mini 3843 permission fix
  Example/Controllers/ViewController.swift
Labels: bug-fix
