Repository rakutentech/ios-miniapp, pull requests merged in 2022-07, with the labels that each got.

#420 [NO TICKET] - Code owners update
  .github/CODEOWNERS
Labels: Refactoring

#422 [MINI-5295] UI freezes when inserting big batch of data
  MiniAppSPM/Sample SPM.xcodeproj/project.pbxproj
  Sample.xcodeproj/project.pbxproj
  Sources/Classes/core/SecureStorage/Database/MiniAppSecureStorageDatabase.swift
  Sources/Classes/core/SecureStorage/Database/MiniAppSecureStorageSqliteDatabase.swift
  Sources/Classes/core/SecureStorage/MiniAppSecureStorage.swift
  Tests/Unit/MiniAppSecureStorageTests.swift
  Tests/Unit/MiniAppStorageTests.swift
Labels: bug, SDK, 4.3.0

#421 [MINI-5284] Storage Exceeded Optimization
  Sources/Classes/core/SecureStorage/Database/MiniAppSecureStorageSqliteDatabase.swift
  Sources/Classes/core/SecureStorage/MiniAppSecureStorage.swift
Labels: bug, Enhancement, 4.3.0

#423 [MINI-5295] Bugfixes: UI freezes when inserting data
  Sources/Classes/core/SecureStorage/Database/MiniAppSecureStorageSqliteDatabase+Model.swift
  Sources/Classes/core/SecureStorage/Database/MiniAppSecureStorageSqliteDatabase.swift
  Sources/Classes/core/SecureStorage/MiniAppSecureStorage.swift
  Tests/Unit/MiniAppSecureStorageTests.swift
Labels: bug, 4.3.0
