Repository rakutentech/ios-miniapp, pull requests merged in 2022-01, with the labels that each got.

#368 [MINI-4355] name email fields fix / naming
  Example/Controllers/Settings/ContactsListSettingsTableViewController.swift
Labels: bug

#370 Deployment Target set to 14.0
  CHANGELOG.md
  MiniApp.podspec
  MiniAppCarthage/MiniApp/MiniApp.h
  MiniAppCarthage/MiniApp/MiniApp.xcodeproj/project.pbxproj
  Podfile
  Podfile.lock
  Sample.xcodeproj/project.pbxproj
  USERGUIDE.md
  fastlane/Fastfile
Labels: Refactoring

#369 Fix/first time launch issue
  Sources/Classes/core/Downloader/MiniAppClient.swift
  Sources/Classes/core/Downloader/MiniAppDownloader.swift
  Sources/Classes/core/Protocols/MiniAppDownloaderProtocol.swift
Labels: bug-fix, SDK

#373 Fix for mini app memory leak
  Sources/Classes/core/Display/RealMiniAppView.swift
Labels: bug-fix, SDK, Major-Change

#372 Refactor Old error types
  Sources/Classes/core/Downloader/DownloadOperation.swift
  Sources/Classes/core/Downloader/ManifestDownloader.swift
  Sources/Classes/core/Downloader/MiniAppClient.swift
  Sources/Classes/core/Downloader/MiniAppDownloader.swift
  Sources/Classes/core/Downloader/MiniAppInfoFetcher.swift
  Sources/Classes/core/MASDKError.swift
  Sources/Classes/core/MiniApp.swift
  Sources/Classes/core/Protocols/MiniAppDownloaderProtocol.swift
  Sources/Classes/core/Protocols/MiniAppMessageDelegate.swift
  Sources/Classes/core/RealMiniApp.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppClientTests.swift
  Tests/Unit/RealMiniAppTests.swift
  Tests/Unit/core/Downloader/ManifestDownloaderTests.swift
  Tests/Unit/core/Downloader/MiniAppDownloaderTests.swift
  Tests/Unit/core/Downloader/MiniAppInfoFetcherTests.swift
Labels: Refactoring, SDK, Major-Change

#376 Fix for Document generation failure
  Sources/Classes/core/Downloader/MiniAppClient.swift
Labels: documentation, bug-fix, SDK

#375 [MINI-4535] Removed all deprecations
  .gitignore
  .swiftlint.yml
  Example/Analytics/Swizzling.swift
  Example/Controllers/Extensions/ViewController+MiniAppMessageProtocol.swift
  Package.resolved
  Podfile.lock
  Sample.xcodeproj/project.pbxproj
  Sample.xcodeproj/xcshareddata/xcschemes/MiniApp_Tests.xcscheme
  Sources/Classes/core/Display/MiniAppExternalWebViewController.swift
  Sources/Classes/core/Display/MiniAppWebView.swift
  Sources/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  Sources/Classes/core/Protocols/MiniAppDownloaderProtocol.swift
  Sources/Classes/core/Protocols/MiniAppMessageDelegate.swift
  Sources/Classes/core/Protocols/MiniAppUserInfoDelegate.swift
  Sources/Classes/core/RealMiniApp.swift
  Sources/Classes/core/Utilities/MASDKLocale.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MASDKLocaleTests.swift
  Tests/Unit/MessageInterfaceExtensionTests.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/RealMiniAppTests.swift
  Tests/Unit/core/Display/MiniAppExternalWebViewControllerTests.swift
  Tests/Unit/core/Downloader/MiniAppDownloaderTests.swift
  fastlane/Fastfile
Labels: SDK, Major-Change

#377 Added Documentation and fixed build issue
  MiniAppCarthage/MiniApp/MiniApp.xcodeproj/project.pbxproj
  Podfile.lock
  Sample.xcodeproj/project.pbxproj
  Sources/Classes/core/Downloader/MiniAppClient.swift
  Sources/Classes/core/Downloader/MiniAppDownloader.swift
  Tests/Unit/Helpers.swift
Labels: documentation, SDK
