Repository rakutentech/ios-miniapp, pull requests merged in 2022-04, with the labels that each got.

#393 [MINI-1732] - In App Purchase implementation
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+MiniAppPurchaseDelegate.swift
  Example/Controllers/ViewController.swift
  MiniApp.podspec
  MiniAppCarthage/MiniApp/MiniApp.xcodeproj/project.pbxproj
  Package.resolved
  Podfile
  Podfile.lock
  Sample.xcodeproj/project.pbxproj
  Sources/Classes/core/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  Sources/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  Sources/Classes/core/MiniAppAnalytics.swift
  Sources/Classes/core/Models/InAppPurchaseResponse.swift
  Sources/Classes/core/Models/MiniAppJavaScriptMessageInfo.swift
  Sources/Classes/core/Protocols/MiniAppMessageDelegate.swift
  Sources/Classes/core/Protocols/MiniAppPurchaseDelegate.swift
  Sources/Classes/core/RealMiniApp.swift
  Sources/Classes/in-app-purchase/MiniAppIAPModule.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
Labels: feature-request, sample-app, SDK, Major-Change

#396 Revert "[MINI-1732] - In App Purchase implementation"
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+MiniAppPurchaseDelegate.swift
  Example/Controllers/ViewController.swift
  MiniApp.podspec
  MiniAppCarthage/MiniApp/MiniApp.xcodeproj/project.pbxproj
  Package.resolved
  Podfile
  Podfile.lock
  Sample.xcodeproj/project.pbxproj
  Sources/Classes/core/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  Sources/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  Sources/Classes/core/MiniAppAnalytics.swift
  Sources/Classes/core/Models/InAppPurchaseResponse.swift
  Sources/Classes/core/Models/MiniAppJavaScriptMessageInfo.swift
  Sources/Classes/core/Protocols/MiniAppMessageDelegate.swift
  Sources/Classes/core/Protocols/MiniAppPurchaseDelegate.swift
  Sources/Classes/core/RealMiniApp.swift
  Sources/Classes/in-app-purchase/MiniAppIAPModule.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
Labels: Revert, feature-branch

#397 [MINI-4968] Secure Storage Implementation
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+MiniAppMessageProtocol.swift
  Example/Controllers/Settings/QASettingsTableViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Settings.storyboard
  MiniAppCarthage/MiniApp/MiniApp.xcodeproj/project.pbxproj
  Sources/Classes/core/Display/RealMiniAppView.swift
  Sources/Classes/core/Extensions/FileManager+MiniApp.swift
  Sources/Classes/core/Extensions/URL+MiniApp.swift
  Sources/Classes/core/Extensions/WKUserContentController+MiniApp.swift
  Sources/Classes/core/JavascriptBridge/MiniAppJavaScriptEnumerations.swift
  Sources/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  Sources/Classes/core/MiniAppAnalytics.swift
  Sources/Classes/core/Models/MiniAppJavaScriptMessageInfo.swift
  Sources/Classes/core/Protocols/MiniAppMessageDelegate.swift
  Sources/Classes/core/Storage/MiniAppSecureStorage.swift
  Sources/Classes/core/Storage/MiniAppStorage.swift
  Tests/Unit/Helpers.swift
  Tests/Unit/MiniAppAdDisplayerTests.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/MiniAppStorageTests.swift
  USERGUIDE.md
Labels: feature-request, SDK
