Repository rakutentech/ios-miniapp, pull requests merged in 2022-11, with the labels that each got.

#445 [MINI-5664] Merge list configuration
  Example/Controllers/SwiftUI/Features/List/MiniAppListView.swift
  Example/Controllers/SwiftUI/Features/List/MiniAppListViewModel.swift
  Example/Controllers/SwiftUI/Features/Settings/MiniAppSettingsView+Config.swift
  Example/Controllers/SwiftUI/Features/Settings/MiniAppSettingsView.swift
  Example/Controllers/SwiftUI/Features/Settings/MiniAppSettingsViewModel.swift
  Example/Controllers/SwiftUI/Features/Single/MiniAppSharePreviewView.swift
  Example/Controllers/SwiftUI/Features/Single/MiniAppSingleView.swift
  Example/Controllers/SwiftUI/Features/Terms/MiniAppTermsView.swift
  Example/Controllers/SwiftUI/Features/Terms/MiniAppWithTermsView.swift
  Example/Controllers/SwiftUI/Features/Terms/MiniAppWithTermsViewModel.swift
  Example/Controllers/SwiftUI/Features/URL/MiniAppUrlView.swift
  Example/Controllers/SwiftUI/Helper/DemoAppAnalytics.swift
  Example/Controllers/SwiftUI/Store/MiniAppPermissionService.swift
  Example/Controllers/SwiftUI/Store/MiniAppStore.swift
  Example/Utils/Config.swift
Labels: feature-request, 5.1.0

#448 Candidate
  CHANGELOG.md
  Sources/Classes/core/MiniApp.swift
Labels: 5.0.0

#447 [MINI-5626] Restore searchable lists
  Example/Controllers/SwiftUI/Features/List/MiniAppListView.swift
  Example/Controllers/SwiftUI/Features/List/MiniAppListViewModel.swift
  Example/Controllers/SwiftUI/Features/Settings/MiniAppSettingsView.swift
  Example/Controllers/SwiftUI/Helper/TextFieldStyle+MiniApp.swift
  Example/Controllers/SwiftUI/Store/MiniAppStore.swift
  Example/SampleApp.swift
  Example/SceneDelegate.swift
Labels: feature-request, 5.1.0

#450 [MINI-5615] Set max storage limit keyboard to number pad and dismiss button for iOS 15
  Example/Controllers/SwiftUI/Features/Settings/Features/MiniAppSettingsQAView.swift
  Example/Controllers/SwiftUI/Helper/TextFieldStyle+MiniApp.swift
Labels: Enhancement, 5.1.0

#451 [MINI-5518] MiniApps restart after permission change
  Example/Controllers/SwiftUI/Features/Single/MiniAppSingleView.swift
Labels: bug-fix, 5.1.0

#449 [MINI-5485, MINI-5695] Missing events for open / close permission settings
  Example/Controllers/SwiftUI/Features/Single/MiniAppSingleView.swift
  Example/Controllers/SwiftUI/Helper/View+Events.swift
  MiniAppSPM/Sample SPM.xcodeproj/project.pbxproj
  Sample.xcodeproj/project.pbxproj
Labels: bug-fix, 5.1.0

#452 [No Ticket]Publishing AppCenter builds from CircleCI
  .circleci/config.yml
  scripts/deploy-to-app-center.sh
Labels: CI, ✓

#454 [MINI-5694] Launch MiniApps when offline
  Example/Controllers/SwiftUI/Features/Single/MiniAppSharePreviewView.swift
  Example/Controllers/SwiftUI/Features/Single/MiniAppSingleView.swift
  Example/Controllers/SwiftUI/Features/Terms/MiniAppWithTermsView.swift
  Example/Controllers/SwiftUI/Features/Terms/MiniAppWithTermsViewModel.swift
  Example/Controllers/SwiftUI/Helper/Reachability.swift
  MiniAppSPM/Sample SPM.xcodeproj/project.pbxproj
  Sample.xcodeproj/project.pbxproj
  Sources/Classes/core/Utilities/Constants.swift
  Sources/Classes/ui/MiniAppSUIView.swift
Labels: bug-fix, 5.1.0

#455 [MINI-5732] Split Appcenter Distribution scripts
  .circleci/config.yml
  README.md
  scripts/deploy-to-app-center.sh
Labels: CI

#456 [NO-TICKET] Fix SwiftLint for SPM Project
  .swiftlint.yml
  MiniAppSPM/Sample SPM.xcodeproj/project.pbxproj
Labels: Enhancement, 5.1.0

#457 [MINI-5710] MiniApp resumed count update on closing web-view
  Sources/Classes/core/Display/MiniAppExternalWebViewController.swift
  Sources/Classes/core/Downloader/MiniAppClient.swift
Labels: SDK, 5.1.0

#458 [MINI-5697] SampleApp Unable to open any contact from settings
  Example/Assets/en.lproj/Localizable.strings
  Example/Controllers/SwiftUI/Features/Settings/Features/MiniAppSettingsContactsView.swift
Labels: bug-fix, 5.1.0

#461 [NO-TICKET] Fastlane simulator issue
  Tests/Unit/MiniAppSecureStorageTests.swift
  fastlane/Fastfile
Labels: 5.1.0

#460 [NO TICKET] miniapp header and permission identifiers
  Example/Controllers/SwiftUI/Features/Single/MiniAppSingleView.swift
  Example/Controllers/SwiftUI/Features/Terms/MiniAppTermsView.swift
  Example/Controllers/SwiftUI/Helper/AccessabilityIdentifiers.swift
Labels: QA

#459 [MINI-5697] Bug Fix for unable to open any contact from settings
  Example/Controllers/SwiftUI/Features/Settings/Features/MiniAppSettingsContactsView.swift
  Sources/Classes/core/Protocols/MiniAppUserInfoDelegate.swift
Labels: bug-fix, 5.1.0
