Repository rakutentech/ios-miniapp, pull requests merged in 2022-06, with the labels that each got.

#408 Fix for CE - Filenames with dot
  Example/Controllers/Extensions/ViewController+MiniAppUserInfoProtocol.swift
  Example/Controllers/Storyboards/Base.lproj/Settings.storyboard
  Example/Utils/String+MiniApp.swift
Labels: bug-fix

#409 [MALI-1042] Save Image Activity Issue
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+Activity.swift
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/Extensions/ViewController+MiniAppUserInfoProtocol.swift
  MiniAppSPM/Sample SPM.xcodeproj/project.pbxproj
  Sample.xcodeproj/project.pbxproj
  Sources/Classes/ui/MiniAppUI.swift
Labels: bug

#404 [MINI-5030] Database for Secure Storage
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MiniApp.podspec
  MiniAppCarthage/MiniApp/MiniApp.xcodeproj/project.pbxproj
  MiniAppSPM/Sample SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
  Podfile.lock
  Sources/Classes/core/Display/RealMiniAppView.swift
  Sources/Classes/core/MiniApp.swift
  Sources/Classes/core/SecureStorage/Database/MiniAppSecureStorageDatabase.swift
  Sources/Classes/core/SecureStorage/Database/MiniAppSecureStorageSqliteDatabase+Model.swift
  Sources/Classes/core/SecureStorage/Database/MiniAppSecureStorageSqliteDatabase.swift
  Sources/Classes/core/SecureStorage/MiniAppSecureStorage+Delegate.swift
  Sources/Classes/core/SecureStorage/MiniAppSecureStorage.swift
  Sources/Classes/core/SecureStorage/MiniAppSecureStorageError.swift
  Sources/Classes/core/SecureStorage/MiniAppSecureStorageSize.swift
  Sources/Classes/core/Storage/MiniAppSecureStorage.swift
  Sources/Classes/core/Storage/MiniAppStorage.swift
  Tests/Unit/MiniAppStorageTests.swift
  USERGUIDE.md
Labels: SDK, feature-branch, 4.2.0

#410 Added support for miniAppTooManyRequestsError
  CHANGELOG.md
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/Settings/SettingsTableViewController.swift
  Example/Controllers/ViewController.swift
  Package.resolved
  Sources/Classes/core/Downloader/MetaDataDownloader.swift
  Sources/Classes/core/Downloader/MiniAppClient.swift
  Sources/Classes/core/Downloader/MiniAppDownloader.swift
  Sources/Classes/core/Downloader/MiniAppInfoFetcher.swift
  Sources/Classes/core/MASDKError.swift
  Sources/Classes/core/Storage/MiniAppStorage.swift
  Sources/Classes/core/Utilities/MASDKLocale.swift
  Sources/Classes/resources/en.lproj/Localizable.strings
  Sources/Classes/resources/ja.lproj/Localizable.strings
  Sources/Classes/ui/MiniAppViewController.swift
  Tests/Unit/MiniAppStorageTests.swift
Labels: sample-app, SDK, feature-branch, 4.2.0

#412 Update File Encryption Secure Storage
  Sources/Classes/core/SecureStorage/Database/MiniAppSecureStorageSqliteDatabase.swift
Labels: Enhancement, 4.2.0

#411 [MALI-1042] Save Image Activity Issue (Bugfix)
  Example/Controllers/Extensions/ViewController+Activity.swift
  MiniAppCarthage/MiniApp/MiniApp.xcodeproj/project.pbxproj
  MiniAppSPM/Sample SPM.xcodeproj/project.pbxproj
  Sample.xcodeproj/project.pbxproj
  Sources/Classes/ui/MiniAppUI+Activity.swift
  Sources/Classes/ui/MiniAppUI.swift
Labels: bug

#413 [MINI-5199] SPM Update RAnalytics to 9.1.0 -> upToNextMajor
  MiniAppSPM/Sample SPM.xcodeproj/project.pbxproj
  MiniAppSPM/Sample SPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Package.swift
Labels: Enhancement

#415 [MINI-5200] [MINI5190] - Fix for Secure storage issue
  Example/Controllers/DisplayController.swift
  Example/Controllers/MAFirstLaunchController.swift
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Sources/Classes/core/SecureStorage/Database/MiniAppSecureStorageSqliteDatabase+Model.swift
  Sources/Classes/core/SecureStorage/MiniAppSecureStorage.swift
  Sources/Classes/ui/MiniAppViewController.swift
Labels: bug-fix, SDK, 4.2.0

#416 Fixing Unit testcases failure for Secure Storage
  Sources/Classes/core/SecureStorage/Database/MiniAppSecureStorageSqliteDatabase+Model.swift
  Sources/Classes/core/SecureStorage/MiniAppSecureStorage.swift
Labels: SDK, 4.2.0

#418 [MINI-5190] - Fix for Navigation bar and framework build
  MiniAppCarthage/MiniApp/MiniApp.xcodeproj/project.pbxproj
  Package.resolved
  Sources/Classes/ui/MiniAppViewController.swift
Labels: sample-app, 4.3.0
