Repository rakutentech/ios-miniapp, pull requests merged in 2022-10, with the labels that each got.

#429 [MINI-5479] Adding close button to share preview
  Example/Controllers/SwiftUI/Features/Single/MiniAppSharePreviewView.swift
  Example/Controllers/SwiftUI/Features/Single/MiniAppSingleView.swift
  Example/Controllers/SwiftUI/Helper/CloseButton.swift
  MiniAppSPM/Sample SPM.xcodeproj/project.pbxproj
  Sample.xcodeproj/project.pbxproj
  Tests/Unit/MiniAppSecureStorageTests.swift
Labels: Enhancement, bug-fix, 5.0.0

#430 [MINI-5519] Include version in getMiniAppInfo
  Sources/Classes/core/View/MiniAppViewHandler.swift
Labels: bug-fix, 5.0.0

#434 [No Ticket] Updated Team
  .github/CODEOWNERS
Labels: github

#431 [MINI-5487] Remove old demo app code
  Example/Analytics/DemoAppAnalytics.swift
  Example/AppDelegate.swift
  Example/Base.lproj/LaunchScreen.xib
  Example/ContentView.swift
  Example/Controllers/ChatContactsSelectorViewController.swift
  Example/Controllers/Deeplink/DeeplinkErrorViewController.swift
  Example/Controllers/DisplayController.swift
  Example/Controllers/DisplayNavigationController.swift
  Example/Controllers/Extensions/ViewController+ChatDelegate.swift
  Example/Controllers/Extensions/ViewController+MiniApp.swift
  Example/Controllers/Extensions/ViewController+MiniAppMessageProtocol.swift
  Example/Controllers/Extensions/ViewController+MiniAppUserInfoProtocol.swift
  Example/Controllers/FirstLaunchViewController.swift
  Example/Controllers/MAFirstLaunchController.swift
  Example/Controllers/Settings/AccessTokenViewController.swift
  Example/Controllers/Settings/ContactsListSettingsTableViewController.swift
  Example/Controllers/Settings/CustomPermissionsListViewController.swift
  Example/Controllers/Settings/DeeplinkListViewController.swift
  Example/Controllers/Settings/GeneralTableViewController.swift
  Example/Controllers/Settings/ManageCustomPermissionsViewController.swift
  Example/Controllers/Settings/PointsSettingsTableViewController.swift
  Example/Controllers/Settings/QASettingsTableViewController.swift
  Example/Controllers/Settings/QueryParamViewController.swift
  Example/Controllers/Settings/SettingsTableViewController.swift
  Example/Controllers/Settings/SignatureSettingsTableViewController.swift
  Example/Controllers/Settings/UserSettingsTableViewController.swift
  Example/Controllers/Storyboards/Base.lproj/Main.storyboard
  Example/Controllers/Storyboards/Base.lproj/Settings.storyboard
  Example/Controllers/Storyboards/Deeplink.storyboard
  Example/Controllers/SwiftUI/Helper/LocationManager.swift
  Example/Controllers/SwiftUI/Helper/MiniAppViewMessageDelegator.swift
  Example/Controllers/SwiftUI/Store/MiniAppStore.swift
  Example/Controllers/ViewController.swift
  Example/Info.plist
  Example/SampleApp.swift
  Example/SceneDelegate.swift
  Example/Utils/Progress+UIViewController.swift
  Example/Utils/UIImageView+Extensions.swift
  Example/Utils/UITableView+EmptyView.swift
  Example/Utils/UITextField.swift
  Example/Utils/UITextView+MiniApp.swift
  Example/Utils/UIView+MiniApp.swift
  Example/Views/MiniAppCell.swift
  MiniAppSPM/Sample SPM.xcodeproj/project.pbxproj
  Podfile.lock
  Sample.xcodeproj/project.pbxproj
  Tests/Unit/MiniAppClientTests.swift
Labels: feature-request, 5.0.0

#436 [No Ticket] Circle CI Setup
  .circleci/config.yml
  Gemfile
  Sample.xcodeproj/project.pbxproj
  fastlane/Fastfile
Labels: CI

#432 [MINI-5414] Cap secure storage file size
  Sources/Classes/core/SecureStorage/MiniAppSecureStorage.swift
  Tests/Unit/MiniAppViewHandlerTests.swift
Labels: bug-fix, ✓, 5.0.0

#439 [MINI-5521] Show clear buttons for settings textfields
  Example/Controllers/SwiftUI/Features/Settings/MiniAppSettingsView.swift
Labels: sample-app, 5.0.0

#440 [MINI-5495] Keyboard overlaps RAS creds when saving
  Example/Controllers/SwiftUI/Features/Settings/MiniAppSettingsView.swift
Labels: sample-app, 5.0.0

#437 [MINI-5484] Add cancel button for close alert
  Example/Controllers/SwiftUI/Features/Single/MiniAppSingleView.swift
Labels: sample-app, 5.0.0

#441 [MINI-5628] Revamp analytics
  Example/Analytics/DemoAppAnalytics.swift
  Example/Analytics/RATController.swift
  Example/Analytics/RATNotificationCenter.swift
  Example/Analytics/Swizzling.swift
  Example/AppDelegate.swift
  Example/Assets/en.lproj/Localizable.strings
  Example/Controllers/SwiftUI/Features/List/MiniAppListView.swift
  Example/Controllers/SwiftUI/Features/MiniAppFeatureListView.swift
  Example/Controllers/SwiftUI/Features/Settings/Features/MiniAppSettingsAccessTokenView.swift
  Example/Controllers/SwiftUI/Features/Settings/Features/MiniAppSettingsContactsView.swift
  Example/Controllers/SwiftUI/Features/Settings/Features/MiniAppSettingsGeneralView.swift
  Example/Controllers/SwiftUI/Features/Settings/Features/MiniAppSettingsPointsView.swift
  Example/Controllers/SwiftUI/Features/Settings/Features/MiniAppSettingsProfileView.swift
  Example/Controllers/SwiftUI/Features/Settings/Features/MiniAppSettingsQAView.swift
  Example/Controllers/SwiftUI/Features/Settings/Features/MiniAppSettingsSignatureView.swift
  Example/Controllers/SwiftUI/Features/Settings/MiniAppSettingsView.swift
  Example/Controllers/SwiftUI/Features/Single/MiniAppSharePreviewView.swift
  Example/Controllers/SwiftUI/Features/Single/MiniAppSingleView.swift
  Example/Controllers/SwiftUI/Features/Terms/MiniAppTermsOptionalCell.swift
  Example/Controllers/SwiftUI/Features/Terms/MiniAppTermsRequiredCell.swift
  Example/Controllers/SwiftUI/Features/Terms/MiniAppTermsView.swift
  Example/Controllers/SwiftUI/Features/URL/MiniAppUrlView.swift
  Example/Controllers/SwiftUI/Helper/View+Tracking.swift
  Example/Controllers/SwiftUI/MiniAppDashboardView.swift
  MiniAppSPM/Sample SPM.xcodeproj/project.pbxproj
  Sample.xcodeproj/project.pbxproj
Labels: sample-app, 5.0.0

#443 [MINI-5628] MiniApp revamp analytics (bugfix)
  Example/Controllers/SwiftUI/Helper/DemoAppAnalytics.swift
  MiniAppSPM/Sample SPM.xcodeproj/project.pbxproj
  Sample.xcodeproj/project.pbxproj
Labels: bug-fix, 5.0.0
