Repository rakutentech/ios-miniapp, pull requests merged in 2023-02, with the labels that each got.

#479 [No Ticket] Changes after the release
  .circleci/config.yml
  Example/Controllers/SwiftUI/Features/Terms/MiniAppTermsView.swift
  MiniApp.podspec
  Sources/Classes/core/MiniApp.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
Labels: 5.2.0

#480 [MINI-5708] Fix for Secure storage notification
  CHANGELOG.md
  Sources/Classes/core/View/MiniAppViewHandler.swift
  Tests/Unit/MiniAppViewHandlerTests.swift
Labels: SDK

#481 [MINI-5871]Mask Project ID & Subscription Key in Settings
  CHANGELOG.md
  Example/Controllers/SwiftUI/Features/Settings/MiniAppSettingsView.swift
Labels: Enhancement, sample-app

#482 [MINI-5895] Fix to show Request Custom permissions
  Example/Controllers/SwiftUI/Helper/MiniAppViewMessageDelegator.swift
Labels: sample-app

#483 [MINI-5895] - Changes to align with Android Error messages
  CHANGELOG.md
  Sources/Classes/core/JavascriptBridge/MiniAppScriptMessageHandler.swift
  Sources/Classes/core/Models/MiniAppJavascriptErrorInfo.swift
  Tests/Unit/MiniAppScriptMessageHandlerTests.swift
  Tests/Unit/Signature/FetcherTests.swift
Labels: SDK, 5.2.0

#484 [MINI-5781] Test cases not reported properly for Xcode 13.4 and above
  Podfile
Labels: sample-app, UT, 5.2.0
